### ISSUE TITLE
CF CLI command restart-app-instance fails with Eirini

### ISSUE THREAD

**Issue by HeavyWombat** [cloudfoundry-incubator/eirini-release#54]
### Description
A `cf restart-app-instance [...]` CLI call fails with Eirini backend.

### Steps to reproduce
```sh
cf push my-app -i 2
cf restart-app-instance my-app 1
```

### What was expected to happen
The respective instance of the app is restarted.

### What actually happened
```
cf restart-app-instance my-app 1
Restarting instance 1 of application my-app as bill@microsoft.com
FAILED
Server error, status code: 500, error code: 10001, message: An unknown error occurred.
```

The cloud controller logs give the following more detailed clue: `undefined method 'stop_index' for #<OPI::Client:0x000055727e125188>`

```json
{
  "timestamp": 1553596199.2098746,
  "message": "Request failed: 500: {
    \"error_code\" : \"UnknownError\", \"description\" : \"An unknown error occurred.\", \"code\" : 10001, \"test_mode_info\" : {
      \"description\" : \"undefined method `stop_index' for #<OPI::Client:0x000055727e125188>\", \"error_code\" : \"CF-stop_index\", \"backtrace\" : [\"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/lib/cloud_controller/diego/messenger.rb:35:in `send_stop_index_request'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:37:in `block in stop_index'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:41:in `with_logging'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:37:in `stop_index'\", \"/var/vcap/packages-src/726cbb2214e138b576700db6a30698edb2b994e2/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/lib/cloud_controller/index_stopper.rb:8:in `stop_index'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/app/controllers/runtime/instances_controller.rb:43:in `kill_instance'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/app/controllers/base/base_controller.rb:86:in `dispatch'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `block in compile!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (2 levels) in route!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1040:in `block in process_route'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `catch'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1038:in `process_route'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:990:in `block in route!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `each'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:989:in `route!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1097:in `block in dispatch!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1094:in `dispatch!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-2.0.6/lib/rack/null_logger.rb:9:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-2.0.6/lib/rack/urlmap.rb:68:in `block in call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `each'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/middleware/request_logs.rb:22:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/middleware/cors.rb:49:in `call_app'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/middleware/cors.rb:14:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:153:in `call'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'\", \"/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/gem_home/ruby/2.4.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"]
    }
  }",
  "log_level": "error",
  "source": "cc.api",
  "data": {
    "request_guid": "8ea55d52-c7ee-4cdc-85d0-8330b52f37fb"
  },
  "thread_id": 46975124543120,
  "fiber_id": 46975122236300,
  "process_id": 1816,
  "file": "/var/vcap/packages-src/fce0f1c91d13120d23750fa007bae6824bbe419c/cloud_controller_ng/lib/sinatra/vcap.rb",
  "lineno": 46,
  "method": "block in registered"
}

```

### Suggested fix (optional)
Implement method `stop_index` in `OPI::Client`.

### Additional information (optional)
We think this use case is not covered in the non-windows multiple instances lifecycle CATs tests.

**Comment by mnitchev** [comment]
Fixed by [this commit in eirini](https://github.com/cloudfoundry-incubator/eirini/commit/8994ad6fc4bca4f4980bc674add618ed0e92d93f) and [this PR in CC](https://github.com/cloudfoundry/cloud_controller_ng/pull/1330) both of which are on master
